import { useMemo, useState } from "react";
import { Download, Printer } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { examMaxMarks, examTypes } from "../data/mockData";
import { useApp } from "../context/AppContext";

const fields = ["test1", "test2", "assignment", "practical", "final"];
const grade = (value) => value >= 90 ? "A+" : value >= 80 ? "A" : value >= 70 ? "B+" : value >= 60 ? "B" : value >= 50 ? "C" : value >= 40 ? "D" : "F";
const averageMark = (assessmentMarks, studentId, subjectCode, exam) => {
  const row = assessmentMarks[studentId]?.[subjectCode]?.[exam] || {};
  const max = examMaxMarks[exam] || {};
  const activeFields = fields.filter((field) => max[field]);
  return Math.round(activeFields.reduce((sum, field) => sum + Number(row[field] || 0), 0) / activeFields.reduce((sum, field) => sum + max[field], 0) * 100);
};

function Reports() {
  const { students, subjects, attendance: attendanceData, assessmentMarks } = useApp();
  const [department, setDepartment] = useState("All");
  const [year, setYear] = useState("All");
  const [section, setSection] = useState("All");
  const [semester, setSemester] = useState("All");
  const [studentId, setStudentId] = useState("All");
  const [status, setStatus] = useState("All");
  const [threshold, setThreshold] = useState(75);
  const reportSubjects = useMemo(() => subjects.filter((item) => semester === "All" || item.semester === semester), [subjects, semester]);
  const filtered = useMemo(() => students.filter((student) => (department === "All" || student.department === department) && (year === "All" || student.year === year) && (section === "All" || student.section === section) && (studentId === "All" || student.id === studentId) && (status === "All" || (status === "At risk" ? student.attendance < threshold : student.attendance >= threshold))), [students, department, year, section, studentId, status, threshold]);
  const averageMarks = Math.round(filtered.reduce((sum, student) => sum + reportSubjects.reduce((subjectSum, item) => subjectSum + averageMark(assessmentMarks, student.id, item.code, examTypes[0]), 0) / (reportSubjects.length || 1), 0) / (filtered.length || 1));
  const attendance = Math.round(filtered.reduce((sum, student) => sum + student.attendance, 0) / (filtered.length || 1));
  const risk = filtered.filter((student) => student.attendance < threshold || averageMark(assessmentMarks, student.id, subjects[0]?.code, examTypes[0]) < 40).length;
  const selected = filtered[0];
  const selectedSubjectData = selected ? reportSubjects.map((item) => ({ name: item.code, attendance: (() => { const rows = Object.values(attendanceData).flatMap((day) => Object.entries(day).filter(([code]) => code === item.code).map(([, values]) => values[selected.id])).filter((value) => typeof value === "boolean"); return rows.length ? Math.round(rows.filter(Boolean).length / rows.length * 100) : selected.attendance; })(), marks: averageMark(assessmentMarks, selected.id, item.code, examTypes[0]) })) : [];
  const progress = selected ? examTypes.map((exam) => ({ exam: exam.replace("Internal Assessment ", "IA "), score: Math.round(reportSubjects.reduce((sum, item) => sum + averageMark(assessmentMarks, selected.id, item.code, exam), 0) / (reportSubjects.length || 1)) })) : [];
  const attendanceRows = selected ? Object.values(attendanceData).flatMap((day) => Object.values(day).map((values) => values[selected.id])).filter((value) => typeof value === "boolean") : [];
  const academicTotal = selected ? selectedSubjectData.reduce((sum, item) => sum + item.marks, 0) : 0;
  const academicAverage = selectedSubjectData.length ? Math.round(academicTotal / selectedSubjectData.length) : 0;
  const best = selectedSubjectData.length ? [...selectedSubjectData].sort((a, b) => b.marks - a.marks)[0] : null;
  const weakest = selectedSubjectData.length ? [...selectedSubjectData].sort((a, b) => a.marks - b.marks)[0] : null;
  const print = () => window.print();

  return <div className="dashboard report-page"><div className="page-header"><div><h1>Reports</h1><p>Combined academic and attendance intelligence.</p></div><div className="header-actions"><button className="secondary-button" onClick={print}><Printer size={16} /> Print</button><button className="primary-button" onClick={() => window.alert("Report generated from current filters.")}><Download size={16} /> Generate Report</button></div></div>
    <div className="report-filters"><label>Department <select className="filter-select" value={department} onChange={(event) => setDepartment(event.target.value)}><option>All</option>{[...new Set(students.map((student) => student.department))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Year <select className="filter-select" value={year} onChange={(event) => setYear(event.target.value)}><option>All</option>{[...new Set(students.map((student) => student.year))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Section <select className="filter-select" value={section} onChange={(event) => setSection(event.target.value)}><option>All</option><option>A</option><option>B</option></select></label><label>Semester <select className="filter-select" value={semester} onChange={(event) => setSemester(event.target.value)}><option>All</option>{[...new Set(subjects.map((item) => item.semester))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Student <select className="filter-select" value={studentId} onChange={(event) => setStudentId(event.target.value)}><option>All</option>{students.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Status <select className="filter-select" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>At risk</option><option>On track</option></select></label><label>Risk below <input type="number" min="0" max="100" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} />%</label></div>
    <div className="stats-grid"><div className="stat-card"><h3>Class Attendance</h3><div className="stat-value">{attendance}%</div><p className="stat-change">Filtered cohort</p></div><div className="stat-card"><h3>Average Marks</h3><div className="stat-value">{averageMarks}%</div><p className="stat-change">Latest assessment</p></div><div className="stat-card"><h3>Students At Risk</h3><div className="stat-value">{risk}</div><p className="stat-change">Attendance or marks</p></div><div className="stat-card"><h3>Students Included</h3><div className="stat-value">{filtered.length}</div><p className="stat-change">Current filters</p></div></div>
    <div className="dashboard-card"><h2>Select a student report</h2><div className="student-report-list">{filtered.map((item) => <button className={`student-report-card ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setStudentId(item.id)}><strong>{item.name}</strong><span>{item.id} · {item.department}</span><small>{item.attendance}% attendance</small></button>)}</div></div>
    <div className="dashboard-grid"><div className="dashboard-card"><h2>Attendance vs marks</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><BarChart data={filtered.map((student) => ({ name: student.name.split(" ")[0], attendance: student.attendance, marks: Math.round(reportSubjects.reduce((sum, item) => sum + averageMark(assessmentMarks, student.id, item.code, examTypes[0]), 0) / (reportSubjects.length || 1)) }))}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis domain={[0, 100]} /><Tooltip /><Bar dataKey="attendance" fill="#2563eb" /><Bar dataKey="marks" fill="#14b8a6" /></BarChart></ResponsiveContainer></div></div><div className="dashboard-card"><h2>Selected student report</h2>{selected ? <><h3>{selected.name} · {selected.id}</h3><p className="muted">{selected.department} · {selected.year} · Section {selected.section}</p><div className="report-detail-grid"><span>Classes <strong>{attendanceRows.length}</strong></span><span>Present <strong>{attendanceRows.filter(Boolean).length}</strong></span><span>Absent <strong>{attendanceRows.filter((value) => !value).length}</strong></span><span>Academic total <strong>{academicTotal}%</strong></span><span>Academic average <strong>{academicAverage}%</strong></span><span>Grade / result <strong>{grade(academicAverage)} · {academicAverage >= 40 ? "Pass" : "Fail"}</strong></span><span>Best area <strong>{best?.name || "—"}</strong></span><span>Weakest area <strong>{weakest?.name || "—"}</strong></span><span>Improvement area <strong>{weakest?.name || "—"}</strong></span></div><div className="progress-item"><span>Attendance ({selected.attendance}%)</span><strong>{attendanceRows.length ? Math.round(attendanceRows.filter(Boolean).length / attendanceRows.length * 100) : 0}%</strong><div className="progress-track"><i style={{ width: `${selected.attendance}%` }} /></div></div><div className="progress-item"><span>Academic average</span><strong>{academicAverage}%</strong><div className="progress-track"><i style={{ width: `${academicAverage}%` }} /></div></div></> : <p className="muted">No student matches the filters.</p>}</div></div>
    {selected && <><div className="dashboard-card"><h2>Complete academic and attendance details</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height={250}><BarChart data={selectedSubjectData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis domain={[0, 100]} /><Tooltip /><Bar dataKey="attendance" fill="#2563eb" /><Bar dataKey="marks" fill="#14b8a6" /></BarChart></ResponsiveContainer></div><div className="table-container"><table><thead><tr><th>Subject</th><th>Faculty</th><th>Attendance</th><th>Marks</th><th>Analysis</th></tr></thead><tbody>{selectedSubjectData.map((item) => <tr key={item.name}><td>{item.name}</td><td>{subjects.find((subject) => subject.code === item.name)?.faculty}</td><td>{item.attendance}%</td><td>{item.marks}%</td><td>{item.attendance < threshold || item.marks < 40 ? "Needs attention" : "On track"}</td></tr>)}</tbody></table></div></div><div className="dashboard-card"><h2>Progress across exams</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height={230}><LineChart data={progress}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="exam" /><YAxis domain={[0, 100]} /><Tooltip /><Line type="monotone" dataKey="score" stroke="#2563eb" strokeWidth={3} /></LineChart></ResponsiveContainer></div></div></>}</div>;
}
export default Reports;
