import { useMemo, useState } from "react";
import { Eye, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useApp } from "../context/AppContext";

const blank = { id: "", name: "", email: "", phone: "", dateOfBirth: "", gender: "Prefer not to say", department: "CSE", year: "1st Year", section: "A", address: "", admissionYear: String(new Date().getFullYear()) };

function Students() {
  const { students, setStudents, saveStudent, deleteStudent: removeStudent } = useApp();
  const [query, setQuery] = useState(""); const [department, setDepartment] = useState("All"); const [year, setYear] = useState("All"); const [section, setSection] = useState("All"); const [status, setStatus] = useState("All"); const [sort, setSort] = useState("name");
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState(false); const [modal, setModal] = useState(false); const [profile, setProfile] = useState(null); const [error, setError] = useState("");
  const visible = useMemo(() => [...students].filter((student) => `${student.name} ${student.id} ${student.email}`.toLowerCase().includes(query.toLowerCase()) && (department === "All" || student.department === department) && (year === "All" || student.year === year) && (section === "All" || student.section === section) && (status === "All" || (status === "At risk" ? student.attendance < 75 : student.attendance >= 75))).sort((a, b) => typeof a[sort] === "number" ? b[sort] - a[sort] : String(a[sort]).localeCompare(String(b[sort]))), [students, query, department, year, section, status, sort]);
  const close = () => { setModal(false); setForm(blank); setEditing(false); setError(""); };
  const open = (student) => { setForm(student ? { ...blank, ...student } : blank); setEditing(Boolean(student)); setModal(true); };
  const submit = async (event) => {
    event.preventDefault();
    if (!form.id.trim() || !form.name.trim() || !form.email.trim() || !form.phone.trim() || !form.department || !form.year || !form.section) return setError("Please complete all required fields.");
    if (!/^\S+@\S+\.\S+$/.test(form.email)) return setError("Enter a valid email address.");
    if (!/^\+?[0-9\s-]{10,15}$/.test(form.phone)) return setError("Enter a valid phone number.");
    if (!editing && students.some((student) => student.id.toLowerCase() === form.id.trim().toLowerCase())) return setError("Student ID already exists.");
    const nextStudent = editing ? { ...form, attendance: students.find((student) => student.id === form.id)?.attendance || 0 } : { ...form, attendance: 100 };
    try {
      await saveStudent(nextStudent, editing);
      setStudents(editing ? students.map((student) => student.id === form.id ? nextStudent : student) : [...students, nextStudent]);
      close();
    } catch (requestError) {
      setError(requestError.message || "Unable to save student.");
    }
  };
  const deleteStudent = async (student) => {
    if (!window.confirm(`Delete ${student.name}? This action cannot be undone.`)) return;
    setError("");
    try {
      await removeStudent(student);
      setStudents((current) => current.filter((item) => item.id !== student.id));
    } catch (requestError) {
      setError(requestError.message || "Unable to delete student.");
    }
  };
  return <div className="dashboard">
    <div className="page-header"><div><h1>Students</h1><p>Manage enrolments, profiles and academic groups.</p></div><button className="primary-button" onClick={() => open()}><Plus size={18} /> Add Student</button></div>
    <div className="dashboard-card"><div className="student-toolbar"><div className="search-box student-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, ID or email..." /></div><select value={department} onChange={(event) => setDepartment(event.target.value)} className="filter-select"><option>All</option><option>CSE</option><option>ECE</option><option>EEE</option><option>MECH</option></select><select value={year} onChange={(event) => setYear(event.target.value)} className="filter-select"><option>All</option>{["1st Year", "2nd Year", "3rd Year", "4th Year"].map((item) => <option key={item}>{item}</option>)}</select><select value={section} onChange={(event) => setSection(event.target.value)} className="filter-select"><option>All</option><option>A</option><option>B</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} className="filter-select"><option>All</option><option>Good</option><option>At risk</option></select><select value={sort} onChange={(event) => setSort(event.target.value)} className="filter-select"><option value="name">Sort: Name</option><option value="attendance">Sort: Attendance</option><option value="department">Sort: Department</option></select></div>
      <div className="table-container"><table><thead><tr><th>Student ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Department</th><th>Year</th><th>Section</th><th>Attendance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((student) => <tr key={student.id}><td>{student.id}</td><td><div className="student-name"><div className="student-avatar">{student.name[0]}</div><strong>{student.name}</strong></div></td><td>{student.email}</td><td>{student.phone}</td><td>{student.department}</td><td>{student.year}</td><td>{student.section}</td><td><span className={student.attendance < 75 ? "attendance low" : "attendance"}>{student.attendance}%</span></td><td><span className={`status-badge ${student.attendance < 75 ? "status-risk" : "status-good"}`}>{student.attendance < 75 ? "At risk" : "Good"}</span></td><td className="nowrap"><button className="icon-button" title="View profile" onClick={() => setProfile(student)}><Eye size={16} /></button><button className="icon-button" title="Edit" onClick={() => open(student)}><Pencil size={16} /></button><button className="icon-button danger" title="Delete" onClick={() => deleteStudent(student)}><Trash2 size={16} /></button></td></tr>)}</tbody></table>{!visible.length && <div className="empty-state">No students match the current search and filters.</div>}</div>
    </div>
    {modal && <div className="modal-overlay"><div className="modal wide-modal"><div className="modal-header"><div><h2>{editing ? "Edit Student" : "Add Student"}</h2><p>Keep student information accurate for reporting.</p></div><button className="modal-close" onClick={close}><X /></button></div><form onSubmit={submit}><div className="form-row">{["id", "name"].map((field) => <div className="form-group" key={field}><label>{field === "id" ? "Student ID" : "Full Name"} *</label><input value={form[field]} disabled={editing && field === "id"} onChange={(event) => setForm({ ...form, [field]: event.target.value })} required /></div>)}</div><div className="form-row">{["email", "phone"].map((field) => <div className="form-group" key={field}><label>{field[0].toUpperCase() + field.slice(1)} *</label><input type={field === "email" ? "email" : "tel"} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} required /></div>)}</div><div className="form-row"><div className="form-group"><label>Date of Birth</label><input type="date" value={form.dateOfBirth} onChange={(event) => setForm({ ...form, dateOfBirth: event.target.value })} /></div><div className="form-group"><label>Gender</label><select value={form.gender} onChange={(event) => setForm({ ...form, gender: event.target.value })}><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></div></div><div className="form-row">{["department", "year", "section"].map((field) => <div className="form-group" key={field}><label>{field[0].toUpperCase() + field.slice(1)} *</label><select value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })}>{field === "department" ? ["CSE", "ECE", "EEE", "MECH"].map((item) => <option key={item}>{item}</option>) : field === "year" ? ["1st Year", "2nd Year", "3rd Year", "4th Year"].map((item) => <option key={item}>{item}</option>) : ["A", "B"].map((item) => <option key={item}>{item}</option>)}</select></div>)}</div><div className="form-row"><div className="form-group"><label>Admission Year</label><input value={form.admissionYear} onChange={(event) => setForm({ ...form, admissionYear: event.target.value })} /></div><div className="form-group"><label>Address</label><input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></div></div>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button">{editing ? "Save Changes" : "Add Student"}</button></div></form></div></div>}
    {profile && <div className="modal-overlay" onClick={() => setProfile(null)}><div className="modal" onClick={(event) => event.stopPropagation()}><div className="modal-header"><div><h2>{profile.name}</h2><p>{profile.id} · {profile.department} · {profile.year}</p></div><button className="modal-close" onClick={() => setProfile(null)}><X /></button></div><div className="profile-details"><b>Contact</b><span>{profile.email}<br />{profile.phone}</span><b>Academic group</b><span>{profile.department} · {profile.year} · Section {profile.section}</span><b>Attendance</b><span>{profile.attendance}% <div className="progress"><div style={{ width: `${profile.attendance}%` }} /></div></span><b>Performance</b><span>Average marks tracked in the Marks module.</span></div></div></div>}
  </div>;
}
export default Students;
